name: QA Workflow

on:
  push:
    branches:
      - QA

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t sjaa2610/project-asg:qa-latest .

    - name: Push Docker image to DockerHub
      run: |
        docker push sjaa2610/project-asg:qa-latest
